"""
plot_style.py — Thesis Figure Style Guide
==========================================
A single source of truth for all matplotlib figures in your thesis.

This script was generated by Claude Sonnet 4.6 with the following prompt: 
"Can you help me make a general style guide for the plots? Like a list of colors, general design elements, etc. 
Perhaps a function that sets the general style, so that I make sure it is the same for each plot"

Usage:
    from plot_style import setup, COLORS, PALETTE

    setup()  # call once per script, before any plotting

    fig, ax = plt.subplots()
    ax.plot(x, y, color=COLORS["blue"])
"""

import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker


# ── Palette ───────────────────────────────────────────────────────────────────
# A cohesive set of named colors.
# Drawn from a muted, print-friendly palette — works in color AND greyscale.

COLORS = {
    # Primary sequence — use in this order for multi-line / multi-bar plots
    "blue":   "#2E6FD9",   # primary accent
    "orange": "#E8821A",   # secondary accent
    "green":  "#2E9E6B",   # tertiary
    "red":    "#D94040",   # error / highlight / ablation
    "purple": "#7B52D9",   # quaternary
    "teal":   "#1FA8A8",   # extra

    # Neutrals
    "grey":        "#888888",   # annotations, secondary lines, baselines
    "light_grey":  "#CCCCCC",   # grid lines, confidence band fills
    "dark":        "#1A1A2E",   # axis labels, tick labels (near-black)
    "background":  "#FFFFFF",   # figure and axes background
}

# Ordered list for cycling (pass to ax.set_prop_cycle or use directly)
PALETTE = [
    COLORS["blue"],
    COLORS["orange"],
    COLORS["green"],
    COLORS["red"],
    COLORS["purple"],
    COLORS["teal"],
]

# Marker styles to pair with colors (useful for accessibility / B&W printing)
MARKERS = ["o", "s", "^", "D", "v", "P"]

# Line styles for a fourth distinguishability axis
LINESTYLES = ["-", "--", "-.", ":", (0, (3, 1, 1, 1)), (0, (5, 2))]


# ── Typography ─────────────────────────────────────────────────────────────────
# LaTeX Computer Modern is the default thesis font; we match it here.
# If you compile without LaTeX rendering, the fallback is "serif".

FONT_FAMILY = "serif"
USE_LATEX   = False          # set False if LaTeX is not installed on your machine

FONT_SIZES = {
    "title":       18,
    "axis_label":  12,
    "tick_label":   9,
    "legend":       9,
    "annotation":   8,
    "caption":      8,
}

# ── Format ────────────────────────────────────────────────────────────────────
PDF_MODE = False

# ── Figure dimensions ─────────────────────────────────────────────────────────
# Match your LaTeX column / text widths.
# Single-column thesis (e.g. 15 cm text width) → use FULL_WIDTH.
# Two-column or side-by-side figures → use HALF_WIDTH.
#
# Golden ratio height is a good default; override per figure as needed.

GOLDEN = 1.618

FULL_WIDTH  = 5.90   # inches  ≈ 15.0 cm  (common single-column text width)
HALF_WIDTH  = 2.87   # inches  ≈  7.3 cm  (two figures side-by-side)
FULL_HEIGHT = FULL_WIDTH / GOLDEN   # ≈ 3.65 in — good default

# Convenience tuples
FIG_FULL  = (FULL_WIDTH, FULL_HEIGHT)   # standard single figure
FIG_HALF  = (HALF_WIDTH, FULL_HEIGHT)   # half-width figure
FIG_WIDE  = (FULL_WIDTH, FULL_WIDTH * 0.5)   # wide / landscape
FIG_SQUARE = (FULL_WIDTH * 0.6, FULL_WIDTH * 0.6)  # confusion matrix etc.


# ── Core setup function ────────────────────────────────────────────────────────

def setup(use_latex: bool = USE_LATEX) -> None:
    """
    Apply the thesis style globally.
    Call once at the top of each plotting script, before creating any figures.

        from plot_style import setup
        setup()
    """

    if use_latex:
        mpl.rcParams["text.usetex"] = True
        mpl.rcParams["text.latex.preamble"] = r"\usepackage{amsmath}"
    else:
        mpl.rcParams["text.usetex"] = False

    mpl.rcParams.update({
        # ── Font ──────────────────────────────────────────────────────────────
        "font.family":          FONT_FAMILY,
        "font.size":            FONT_SIZES["tick_label"],
        "axes.titlesize":       FONT_SIZES["title"],
        "axes.labelsize":       FONT_SIZES["axis_label"],
        "xtick.labelsize":      FONT_SIZES["tick_label"],
        "ytick.labelsize":      FONT_SIZES["tick_label"],
        "legend.fontsize":      FONT_SIZES["legend"],
        "legend.title_fontsize": FONT_SIZES["legend"],

        # ── Color cycle ───────────────────────────────────────────────────────
        "axes.prop_cycle": mpl.cycler(color=PALETTE),

        # ── Figure ────────────────────────────────────────────────────────────
        "figure.figsize":       FIG_FULL,
        "figure.dpi":           150,        # screen preview quality
        "savefig.dpi":          300,        # output quality
        "savefig.format":       "pdf",
        "savefig.bbox":         "tight",
        "savefig.pad_inches":   0.05,
        "figure.facecolor":     COLORS["background"],

        # ── Axes ──────────────────────────────────────────────────────────────
        "axes.facecolor":       COLORS["background"],
        "axes.edgecolor":       COLORS["dark"],
        "axes.linewidth":       0.8,
        "axes.grid":            True,
        "axes.axisbelow":       True,       # grid behind data
        "axes.spines.top":      False,      # clean look: remove top spine
        "axes.spines.right":    False,      # remove right spine

        # ── Grid ──────────────────────────────────────────────────────────────
        "grid.color":           COLORS["light_grey"],
        "grid.linewidth":       0.5,
        "grid.linestyle":       "--",
        "grid.alpha":           0.7,

        # ── Lines ─────────────────────────────────────────────────────────────
        "lines.linewidth":      1.5,
        "lines.markersize":     5,

        # ── Legend ────────────────────────────────────────────────────────────
        "legend.frameon":       True,
        "legend.framealpha":    1.0,
        "legend.facecolor":     COLORS["background"],
        "legend.edgecolor":     COLORS["grey"],
        "legend.borderpad":     0.4,
        "legend.labelspacing":  0.3,
        "legend.loc":           "best",
        "legend.fancybox":      True,
        "legend.shadow":        False,

        # ── Ticks ─────────────────────────────────────────────────────────────
        "xtick.direction":      "out",
        "ytick.direction":      "out",
        "xtick.major.width":    0.8,
        "ytick.major.width":    0.8,
        "xtick.minor.visible":  False,
        "ytick.minor.visible":  False,
    })


# ── Helper utilities ───────────────────────────────────────────────────────────

def save(fig: plt.Figure, path: str, **kwargs) -> None:
    """
    Save a figure to PDF/PNG with thesis defaults.

        save(fig, "figures/accuracy_curve")   # saves accuracy_curve.pdf

    Extra kwargs are forwarded to fig.savefig().
    """

    formatting = "pdf" if PDF_MODE else "png"
    if not path.endswith(f".{formatting}"):
        path = path + f".{formatting}"
    fig.savefig(path, format=formatting, **kwargs)
    print(f"  → saved {path}")


def label_bars(ax: plt.Axes, fmt: str = "{:.2f}", padding: float = 0.01) -> None:
    """
    Annotate each bar in a bar chart with its value.

        label_bars(ax)
        label_bars(ax, fmt="{:.1%}")   # percentage labels
    """
    y_max = max(p.get_height() for p in ax.patches)
    for patch in ax.patches:
        h = patch.get_height()
        ax.text(
            patch.get_x() + patch.get_width() / 2,
            h + y_max * padding,
            fmt.format(h),
            ha="center", va="bottom",
            fontsize=FONT_SIZES["annotation"],
            color=COLORS["dark"],
        )


def add_baseline(ax: plt.Axes, y: float, label: str = "Baseline") -> None:
    """
    Draw a dashed horizontal baseline (e.g. random chance, previous SOTA).

        add_baseline(ax, y=0.5, label="Random chance")
    """
    ax.axhline(
        y, linestyle="--", linewidth=1.0,
        color=COLORS["grey"], zorder=1,
        label=label,
    )


def confidence_band(
    ax: plt.Axes,
    x,
    mean,
    std,
    color: str | None = None,
    alpha: float = 0.15,
) -> None:
    """
    Shade a ±1 std confidence band around a mean curve.

        confidence_band(ax, epochs, mean_acc, std_acc, color=COLORS["blue"])
    """
    if color is None:
        color = PALETTE[0]
    ax.fill_between(x, mean - std, mean + std, color=color, alpha=alpha)


# ── Quick demo ────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import numpy as np

    setup()

    x = np.linspace(0, 10, 100)
    fig, axes = plt.subplots(1, 2, figsize=(FULL_WIDTH, FULL_HEIGHT))

    # Left: multi-line with confidence bands
    ax = axes[0]
    for i, (name, color, marker) in enumerate(
        zip(["Model A", "Model B", "Model C"], PALETTE, MARKERS)
    ):
        mean = np.sin(x - i * 0.5) * np.exp(-x * 0.05) + i * 0.2
        std  = 0.05 + 0.02 * np.random.rand(len(x))
        ax.plot(x, mean, label=name, color=color, marker=marker, markevery=15)
        confidence_band(ax, x, mean, std, color=color)

    add_baseline(ax, y=0.0, label="Baseline")
    ax.set_xlabel("Epoch")
    ax.set_ylabel("Validation Accuracy")
    ax.set_title("Training Curves")
    ax.legend()

    # Right: bar chart
    ax = axes[1]
    models = ["MLP", "CNN", "ResNet", "Ours"]
    scores = [0.72, 0.81, 0.88, 0.93]
    bars = ax.bar(models, scores, color=PALETTE[:4], width=0.55)
    label_bars(ax, fmt="{:.2f}")
    add_baseline(ax, y=0.50, label="Random")
    ax.set_ylim(0, 1.05)
    ax.set_ylabel("Test Accuracy")
    ax.set_title("Model Comparison")
    ax.legend()

    fig.tight_layout()
    save(fig, "demo_style_guide")
    plt.show()